### ISSUE TITLE
PSADv1: specify the content body using "mediatype", not "resource"

### ISSUE THREAD

**Issue by automatthew** [pandastrike/panda-sky#103]
The first round of work, for expedience, specifies the schema for the request or response body using a reference to a key in the dictionary of JSON Schemas.

```yaml
resources:
  blurbs:
    path: /blurbs
    description: "Virtual collection of blurbs"
    methods:
      POST:
        signatures:
          request:
            resource: blurb
          response:
            status: [201, 400]
schema:
  blurb:
    $schema: "http://json-schema.org/draft-04/schema"
    title: Blurb
    type: object
    properties:
      content:
        type: string
      expiration:
        type: string
        format: date-time
```

Using a media-type is preferable, and part of the original redesign for PSAD.

**Comment by dyoder** [comment]
Maybe the indirection is kind of nice? We'd still need to add `mediaType` to the schema, but we'd look it up when constructing the API GW template. It's always been a little bit annoying to have to put the full media type in the signature. The only trouble with this is versioning, since the media type may include a version attribute. But we could introduce a version attribute in the signature.

Another possibility would be to construct the media type via convention, ex:

`application/vnd.{{vendor}}.{{resource}};charset={{charset}};version={{version}}`

where `vendor` and `charset` are perhaps set in `sky.yaml` (`charset` could default to `utf-8`). 

That is, rather than burden the developer with figuring this out, we just do the right thing by default. Later, we could (if people demand it), add a `mediaType` attribute either to the schema or to the signature to override the convention.

Also, technically, we will want eventually to allow for an arrays of types in the signature. Or perhaps an array of versions? So we'd end up with something like this:

```json-schema
resources:
  blurbs:
    path: /blurbs
    description: "Virtual collection of blurbs"
    methods:
      POST:
        signatures:
          request:
            resource: blurb
            # this is the part that's changed
            versions: [1, 2]
          response:
            status: [201, 400]
schema:
  blurb:
    $schema: "http://json-schema.org/draft-04/schema"
    title: Blurb
    type: object
    properties:
      content:
        type: string
      expiration:
        type: string
        format: date-time
```

**Comment by automatthew** [comment]
We should definitely have multiple mediatypes allowed for request/response bodies.

In addition to having `signatures.request.mediatype`, we can have `signatures.request.schema`, with the value being a JSON Pointer to a particular schema, either relative to the one we define, or fully specified as a URL:

```yaml
signatures:
  request:
    schema:
      - "#/blurb"
      - "https://schema.blurb9.com/v1#blurb"
```
