### ISSUE TITLE
Design generic Request Mapping format

### ISSUE THREAD

**Issue by automatthew** [pandastrike/panda-sky#62]
Proposal for the structure of the object that is passed to the AWS Lambda handler function in Node.js

```yaml
url:
  path:
    account: wyrdspirits
  query:
    campaignID: a93f15c7081
method: PATCH
headers:
  Authorization: PandaGuard z=asdfi8092,yy=akdflasdidfms,d=4tnookie
  Content-Type: application/vnd.pandamarket.campaign_update+json
  Accept: application/vnd.pandamarket.campaign_view+json
content: # Might be a Buffer or other non-Object
  startTime: 1094057845748
  spend: 40000
  proof: 107
```

**Comment by automatthew** [comment]
For our present needs, this can be interleaved with the existing objects, to avoid breaking our apps.


```yaml
key: dice-ware-correct-horse-assault-needful
url: ...
method: POST
headers: ...
content: ...
```
