### ISSUE TITLE
Mapping Template for Panda Request Representation

### ISSUE THREAD

**Issue by automatthew** [pandastrike/panda-sky#63]
In our AWS Lambda handlers, we often want access to all the dimensions of an HTTP request:  path params, query params, headers.  We can use a Mapping Template in the Integration Request to achieve this.

For now, we will do this simply for "application/json".  Later we can generate Mapping Templates for each custom media type we use, which will allow us to whitelist query params and headers if desired.

In an effort to avoid breaking existing applications, we may want to continue expressing the params at the top level, as done at present.

```yaml
url:
  path:
    account: wyrdspirits
  query:
    campaignID: a93f15c7081
method: PATCH
headers:
  Authorization: PandaGuard z=asdfi8092,yy=akdflasdidfms,d=4tnookie
  Content-Type: application/vnd.pandamarket.campaign_update+json
  Accept: application/vnd.pandamarket.campaign_view+json
content: # Might be a Buffer or other non-Object
  startTime: 1094057845748
  spend: 40000
  proof: 107
```
